name: ESLint
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo npm install -g eslint
    - name: Run ESLint
      run: eslint $(git ls-files '*.js')

